### ISSUE TITLE
User can define empty transactions

### ISSUE THREAD

**Issue by SheidaMohassesy** [SiaQnbr/keepcent#14]
We expect to validate `title`, `value` and `category` before adding them to transaction list, but it seems it is not validating at all.

https://user-images.githubusercontent.com/44509767/187468521-fbc7e799-bf59-42a7-8bcc-7f58d3dc9a05.mov

**Comment by SiaExplains** [comment]
Thanks @SheidaM , I'll handle it soon 🤞

**Comment by SiaExplains** [comment]
I resolved this issue quickly but not efficiently for now by this PR =>
https://github.com/SiaQnbr/expense-tracker/pull/15
